version: '2'
services:
  web:
    build: .
    command: >
      sh -c "npm run build && npm run migrate && npm run start"
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: legendcity
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: legendcity-test
